services:
  foundry:
    image: felddy/foundryvtt:13
    hostname: my_foundry_host
    volumes:
      - type: bind
        source: /data
        target: /data
    environment:
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json
